// <auto-generated />
using CMI.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CMI.Model.Migrations
{
    [DbContext(typeof(CmiDataContext))]
    [Migration("20251227090031_cmi-001")]
    partial class cmi001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("INSPECTION_TERM_CODE_SEQ");

            modelBuilder.Entity("CMI.Model.Entities.InspectionGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<long?>("DeactivationDate")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("DEACTIVATION_DATE");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("TITLE");

                    b.HasKey("Id");

                    b.ToTable("INSPECTION_GROUP", (string)null);
                });

            modelBuilder.Entity("CMI.Model.Entities.InspectionSubGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<long?>("DeactivationDate")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("DEACTIVATION_DATE");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<long>("InspectionGroupId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("INSPECTION_GROUP_ID");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("TITLE");

                    b.HasKey("Id");

                    b.HasIndex("InspectionGroupId");

                    b.ToTable("INSPECTION_SUB_GROUP", (string)null);
                });

            modelBuilder.Entity("CMI.Model.Entities.LevelByHatef", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TITLE");

                    b.HasKey("Id");

                    b.ToTable("LEVEL_BY_HATEF", (string)null);
                });

            modelBuilder.Entity("FIS.SQL_Oracle.Entities.Error", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<string>("ExceptionData")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EXCEPTION_DATA");

                    b.Property<string>("ExtraData")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EXTRA_DATA");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.HasKey("Id");

                    b.ToTable("ERROR", (string)null);
                });

            modelBuilder.Entity("FIS.SQL_Oracle.Entities.Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("ACTION");

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.Property<string>("RecordData")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RECORD_DATA");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("TABLE_NAME");

                    b.HasKey("Id");

                    b.ToTable("LOG", (string)null);
                });

            modelBuilder.Entity("CMI.Model.Entities.InspectionSubGroup", b =>
                {
                    b.HasOne("CMI.Model.Entities.InspectionGroup", "InspectionGroup")
                        .WithMany("InspectionSubGroups")
                        .HasForeignKey("InspectionGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InspectionGroup");
                });

            modelBuilder.Entity("CMI.Model.Entities.InspectionGroup", b =>
                {
                    b.Navigation("InspectionSubGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
