// <auto-generated />
using CMI.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CMI.Model.Migrations
{
    [DbContext(typeof(CmiDataContext))]
    [Migration("20260112045554_cmi-002")]
    partial class cmi002
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("INSPECTION_TERM_CODE_SEQ");

            modelBuilder.Entity("CMI.Model.Entities.Attachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttachmentCategoryId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FILENAME");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.Property<long>("RecordId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("RECORD_ID");

                    b.Property<string>("SanaId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("NVARCHAR2(36)")
                        .HasColumnName("SANA_ID");

                    b.Property<int>("TableId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TABLE_ID");

                    b.HasKey("Id");

                    b.ToTable("ATTACHMENT", (string)null);
                });

            modelBuilder.Entity("CMI.Model.Entities.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TITLE");

                    b.HasKey("Id");

                    b.ToTable("CITY", (string)null);
                });

            modelBuilder.Entity("CMI.Model.Entities.FamilyRelationship", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<int>("FamilyRelationshipId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FAMILY_RELATIONSHIP_ID");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("FULL_NAME");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.Property<long>("RecordId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("TableId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("FAMILY_RELATIONSHIP", (string)null);
                });

            modelBuilder.Entity("CMI.Model.Entities.InspectionGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<long?>("DeactivationDate")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("DEACTIVATION_DATE");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("TITLE");

                    b.HasKey("Id");

                    b.ToTable("INSPECTION_GROUP", (string)null);
                });

            modelBuilder.Entity("CMI.Model.Entities.InspectionSubGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<long?>("DeactivationDate")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("DEACTIVATION_DATE");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<long>("InspectionGroupId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("INSPECTION_GROUP_ID");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("TITLE");

                    b.HasKey("Id");

                    b.HasIndex("InspectionGroupId");

                    b.ToTable("INSPECTION_SUB_GROUP", (string)null);
                });

            modelBuilder.Entity("CMI.Model.Entities.LevelByHatef", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TITLE");

                    b.HasKey("Id");

                    b.ToTable("LEVEL_BY_HATEF", (string)null);
                });

            modelBuilder.Entity("CMI.Model.Entities.Student", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    b.Property<long>("BirthDate")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("BIRTH_DATE");

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<long>("CityId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CITY_ID");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("LAST_NAME");

                    b.Property<long>("LevelId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LEVEL_ID");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("LevelId");

                    b.ToTable("STUDENT", (string)null);
                });

            modelBuilder.Entity("CMI.Model.Entities.Teacher", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    b.Property<long>("BirthDate")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("BIRTH_DATE");

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<long>("CityId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CITY_ID");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("LAST_NAME");

                    b.Property<long>("LevelId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LEVEL_ID");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("LevelId");

                    b.ToTable("TEACHER", (string)null);
                });

            modelBuilder.Entity("FIS.SQL_Oracle.Entities.Error", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<string>("ExceptionData")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EXCEPTION_DATA");

                    b.Property<string>("ExtraData")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EXTRA_DATA");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.HasKey("Id");

                    b.ToTable("ERROR", (string)null);
                });

            modelBuilder.Entity("FIS.SQL_Oracle.Entities.Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("ACTION");

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.Property<string>("RecordData")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RECORD_DATA");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("TABLE_NAME");

                    b.HasKey("Id");

                    b.ToTable("LOG", (string)null);
                });

            modelBuilder.Entity("CMI.Model.Entities.InspectionSubGroup", b =>
                {
                    b.HasOne("CMI.Model.Entities.InspectionGroup", "InspectionGroup")
                        .WithMany("InspectionSubGroups")
                        .HasForeignKey("InspectionGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InspectionGroup");
                });

            modelBuilder.Entity("CMI.Model.Entities.Student", b =>
                {
                    b.HasOne("CMI.Model.Entities.City", "City")
                        .WithMany("Students")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMI.Model.Entities.LevelByHatef", "Level")
                        .WithMany("Students")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("CMI.Model.Entities.EducationalQualification", "EducationalQualification", b1 =>
                        {
                            b1.Property<long>("ID")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("NUMBER(19)");

                            OraclePropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("ID"));

                            b1.Property<string>("Educational")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("NVARCHAR2(100)")
                                .HasColumnName("EDUCATIONAL");

                            b1.Property<long>("StudentId")
                                .HasColumnType("NUMBER(19)");

                            b1.HasKey("ID");

                            b1.HasIndex("StudentId");

                            b1.ToTable("STUDENT_EDUCATIONAL_QUALIFICATION", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StudentId");

                            b1.OwnsOne("CMI.Model.Entities.Score", "Score", b2 =>
                                {
                                    b2.Property<long>("EducationalQualificationID")
                                        .HasColumnType("NUMBER(19)");

                                    b2.Property<float>("Value")
                                        .HasColumnType("BINARY_FLOAT")
                                        .HasColumnName("EDUCATIONAL_SCORE");

                                    b2.HasKey("EducationalQualificationID");

                                    b2.ToTable("STUDENT_EDUCATIONAL_QUALIFICATION");

                                    b2.WithOwner()
                                        .HasForeignKey("EducationalQualificationID");
                                });

                            b1.Navigation("Score")
                                .IsRequired();
                        });

                    b.Navigation("City");

                    b.Navigation("EducationalQualification");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("CMI.Model.Entities.Teacher", b =>
                {
                    b.HasOne("CMI.Model.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMI.Model.Entities.LevelByHatef", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("CMI.Model.Entities.City", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("CMI.Model.Entities.InspectionGroup", b =>
                {
                    b.Navigation("InspectionSubGroups");
                });

            modelBuilder.Entity("CMI.Model.Entities.LevelByHatef", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
