// <auto-generated />
using CMI.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CMI.Model.Migrations
{
    [DbContext(typeof(CmiDataContext))]
    partial class CmiDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("INSPECTION_TERM_CODE_SEQ");

            modelBuilder.Entity("CMI.Model.Entities.BranchInspectionDayAllocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchDegreeId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("BRANCH_DEGREE_ID");

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<long?>("DeactivationDate")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("DEACTIVATION_DATE");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<short>("InspectionDayNumber")
                        .HasColumnType("NUMBER(5)")
                        .HasColumnName("INSPECTION_DAY_NUMBER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.HasKey("Id");

                    b.ToTable("BRANCH_INSPECTION_DAY_ALLOCATION", (string)null);
                });

            modelBuilder.Entity("CMI.Model.Entities.BranchManagementTeamAllocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<long?>("DeactivationDate")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("DEACTIVATION_DATE");

                    b.Property<long>("InspectorProfileId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("INSPECTOR_PROFILE_ID");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.Property<int>("ReferralGroupId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("REFERRAL_GROUP_ID");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("REGION_CODE");

                    b.HasKey("Id");

                    b.HasIndex("InspectorProfileId");

                    b.ToTable("BRANCH_MANAGEMENT_TEAM_ALLOCATION", (string)null);
                });

            modelBuilder.Entity("CMI.Model.Entities.CalendarSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<long>("HolidayDate")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("HOLIDAY_DATE");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.Property<int>("Year")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("YEAR");

                    b.HasKey("Id");

                    b.ToTable("CALENDAR_SETTING", (string)null);
                });

            modelBuilder.Entity("CMI.Model.Entities.Distance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<long?>("DeactivationDate")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("DEACTIVATION_DATE");

                    b.Property<string>("FromUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("FROM_UNIT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool?>("IsConvert")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_CONVERT");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.Property<string>("ToRegion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("TO_REGION");

                    b.Property<string>("ToUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("TO_UNIT");

                    b.Property<long>("Value")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("VALUE");

                    b.HasKey("Id");

                    b.ToTable("DISTANCE", (string)null);
                });

            modelBuilder.Entity("CMI.Model.Entities.InspectionGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<long?>("DeactivationDate")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("DEACTIVATION_DATE");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("TITLE");

                    b.HasKey("Id");

                    b.ToTable("INSPECTION_GROUP", (string)null);
                });

            modelBuilder.Entity("CMI.Model.Entities.InspectionPeriod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<long?>("DeactivationDate")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("DEACTIVATION_DATE");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<long>("FromDate")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("FROM_DATE");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("TITLE");

                    b.Property<long>("ToDate")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("TO_DATE");

                    b.Property<short>("Year")
                        .HasColumnType("NUMBER(5)")
                        .HasColumnName("YEAR");

                    b.HasKey("Id");

                    b.ToTable("INSPECTION_PERIOD", (string)null);
                });

            modelBuilder.Entity("CMI.Model.Entities.InspectionSubGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<long?>("DeactivationDate")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("DEACTIVATION_DATE");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<long>("InspectionGroupId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("INSPECTION_GROUP_ID");

                    b.Property<long?>("InspectorProfileId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("TITLE");

                    b.HasKey("Id");

                    b.HasIndex("InspectionGroupId");

                    b.HasIndex("InspectorProfileId");

                    b.ToTable("INSPECTION_SUB_GROUP", (string)null);
                });

            modelBuilder.Entity("CMI.Model.Entities.InspectorEvaluation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<int>("EvaluationTerm")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EVALUATION_TERM");

                    b.Property<long>("InspectorProfileId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("INSPECTOR_PROFILE_ID");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.Property<decimal>("Score")
                        .HasMaxLength(10)
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("SCORE");

                    b.Property<int>("Year")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("YEAR");

                    b.HasKey("Id");

                    b.HasIndex("InspectorProfileId");

                    b.ToTable("INSPECTOR_EVALUATION", (string)null);
                });

            modelBuilder.Entity("CMI.Model.Entities.InspectorGroupRelation", b =>
                {
                    b.Property<long>("InspectorProfileId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("INSPECTOR_PROFILE_ID");

                    b.Property<long>("InspectionSubGroupId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("INSPECTION_SUB_GROUP_ID");

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<long>("Id")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.HasKey("InspectorProfileId", "InspectionSubGroupId");

                    b.HasIndex("InspectionSubGroupId");

                    b.ToTable("INSPECTOR_GROUP_RELATION", (string)null);
                });

            modelBuilder.Entity("CMI.Model.Entities.InspectorProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("ADDRESS");

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<int?>("DayOff")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DAY_OFF");

                    b.Property<long>("EmployementDate")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("EMPLOYEMENT_DATE");

                    b.Property<long>("FromDate")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("FROM_DATE");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.Property<string>("PersonelCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("PERSONEL_CODE");

                    b.Property<string>("PersonnelName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("INSPECTOR_PERSONNEL_NAME");

                    b.Property<int>("ProfileTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(1)
                        .HasColumnName("PROFILE_TYPE_ID");

                    b.Property<string>("SignatureFileName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SIGNATURE_FILE_NAME");

                    b.Property<string>("SignatureSanaFileId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("NVARCHAR2(36)")
                        .HasColumnName("SIGNATURE_SANA_FILE_ID");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<long?>("ToDate")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("TO_DATE");

                    b.HasKey("Id");

                    b.ToTable("INSPECTOR_PROFILE", (string)null);
                });

            modelBuilder.Entity("CMI.Model.Entities.InspectorProfileReferralGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<long?>("DeactivationDate")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("DEACTIVATION_DATE");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<long>("InspectorProfileId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("INSPECTOR_PROFILE_ID");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.Property<int>("ReferralGroupId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("REFERRAL_GROUP_ID");

                    b.HasKey("Id");

                    b.HasIndex("InspectorProfileId");

                    b.ToTable("INSPECTOR_PROFILE_REFERRAL_GROUP", (string)null);
                });

            modelBuilder.Entity("CMI.Model.Entities.InspectorRoleRelation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<long>("InspectorProfileId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.Property<int>("Role")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ROLE");

                    b.HasKey("Id");

                    b.HasIndex("InspectorProfileId");

                    b.ToTable("INSPECTOR_ROLE_RELATION", (string)null);
                });

            modelBuilder.Entity("CMI.Model.Entities.TestYeKe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Black")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("BLACK");

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.Property<string>("Tick")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TICK");

                    b.Property<string>("White")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(4000)")
                        .HasColumnName("WHITE");

                    b.HasKey("Id");

                    b.ToTable("TEST_YEKE", (string)null);
                });

            modelBuilder.Entity("FIS.SQL_Oracle.Entities.Error", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<string>("ExceptionData")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EXCEPTION_DATA");

                    b.Property<string>("ExtraData")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EXTRA_DATA");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.HasKey("Id");

                    b.ToTable("ERROR", (string)null);
                });

            modelBuilder.Entity("FIS.SQL_Oracle.Entities.Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("ACTION");

                    b.Property<long>("CREATED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CREATED_VIA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CREATED_VIA");

                    b.Property<long?>("LAST_EDITED_AT")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LAST_EDITED_AT");

                    b.Property<string>("LAST_EDITED_VIA")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("LAST_EDITED_VIA");

                    b.Property<string>("LAST_EDITOR_BY")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("LAST_EDITOR_BY");

                    b.Property<string>("RecordData")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RECORD_DATA");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("TABLE_NAME");

                    b.HasKey("Id");

                    b.ToTable("LOG", (string)null);
                });

            modelBuilder.Entity("CMI.Model.Entities.BranchManagementTeamAllocation", b =>
                {
                    b.HasOne("CMI.Model.Entities.InspectorProfile", "InspectorProfile")
                        .WithMany("BranchManagementTeamAllocations")
                        .HasForeignKey("InspectorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InspectorProfile");
                });

            modelBuilder.Entity("CMI.Model.Entities.InspectionSubGroup", b =>
                {
                    b.HasOne("CMI.Model.Entities.InspectionGroup", "InspectionGroup")
                        .WithMany("InspectionSubGroups")
                        .HasForeignKey("InspectionGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMI.Model.Entities.InspectorProfile", null)
                        .WithMany("InspectionSubGroups")
                        .HasForeignKey("InspectorProfileId");

                    b.Navigation("InspectionGroup");
                });

            modelBuilder.Entity("CMI.Model.Entities.InspectorEvaluation", b =>
                {
                    b.HasOne("CMI.Model.Entities.InspectorProfile", "InspectorProfile")
                        .WithMany("InspectorEvaluations")
                        .HasForeignKey("InspectorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InspectorProfile");
                });

            modelBuilder.Entity("CMI.Model.Entities.InspectorGroupRelation", b =>
                {
                    b.HasOne("CMI.Model.Entities.InspectionSubGroup", "InspectionSubGroup")
                        .WithMany("InspectorGroupRelations")
                        .HasForeignKey("InspectionSubGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMI.Model.Entities.InspectorProfile", "InspectorProfile")
                        .WithMany("InspectorGroupRelations")
                        .HasForeignKey("InspectorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InspectionSubGroup");

                    b.Navigation("InspectorProfile");
                });

            modelBuilder.Entity("CMI.Model.Entities.InspectorProfileReferralGroup", b =>
                {
                    b.HasOne("CMI.Model.Entities.InspectorProfile", "InspectorProfile")
                        .WithMany("InspectorProfileReferralGroups")
                        .HasForeignKey("InspectorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InspectorProfile");
                });

            modelBuilder.Entity("CMI.Model.Entities.InspectorRoleRelation", b =>
                {
                    b.HasOne("CMI.Model.Entities.InspectorProfile", "InspectorProfile")
                        .WithMany("InspectorRoleRelations")
                        .HasForeignKey("InspectorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InspectorProfile");
                });

            modelBuilder.Entity("CMI.Model.Entities.InspectionGroup", b =>
                {
                    b.Navigation("InspectionSubGroups");
                });

            modelBuilder.Entity("CMI.Model.Entities.InspectionSubGroup", b =>
                {
                    b.Navigation("InspectorGroupRelations");
                });

            modelBuilder.Entity("CMI.Model.Entities.InspectorProfile", b =>
                {
                    b.Navigation("BranchManagementTeamAllocations");

                    b.Navigation("InspectionSubGroups");

                    b.Navigation("InspectorEvaluations");

                    b.Navigation("InspectorGroupRelations");

                    b.Navigation("InspectorProfileReferralGroups");

                    b.Navigation("InspectorRoleRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
