ALTER TABLE "BRANCH_MANAGEMENT_TEAM_ALLOCATION" DROP CONSTRAINT "FK_BRANCH_MANAGEMENT_TEAM_ALLOCATION_REFERRAL_GROUP_REFERRAL_GROUP_ID"
/

DROP INDEX "IX_BRANCH_MANAGEMENT_TEAM_ALLOCATION_REFERRAL_GROUP_ID"
/

INSERT INTO "EF_MIGRATION_HISTORY" ("MigrationId", "ProductVersion")
VALUES (N'20251214074005_cmi-020', N'9.0.5')
/

